name: todoapp-ci
run-name: ${{ github.actor }} - ${{ github.ref_name }} - ${{ github.sha }}

on: 
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main"]

env:
    PYTHON_VERSION: 3.8

jobs:
    python-ci:
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: ./src

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Python ${{ env.PYTHON_VERSION }}
              uses: actions/setup-python@v4
              with:
                python-version: ${{ env.PYTHON_VERSION}}

            - name: Install Dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
                pip install flake8 coverage

            - name: Run tests
              run: |
                coverage run manage.py test -v2

            - name: Show coverage report
              run: |
                coverage report -m

            - name: Lint
              run: |
                flake8 . --show-source --statistics

            - name: Check Complexity
              run: |
                flake8 . --statistics --max-complexity=10 --exit-zero

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: python-code
                path: ./src
